# Generated by Django 4.2.5 on 2023-09-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.IntegerField(primary_key=True, serialize=False)),
                ('tp_conta', models.CharField(choices=[('Poupança', 'Poupanca'), ('Corrente', 'Corrente')], max_length=30)),
                ('banco', models.CharField(choices=[('Banco 1', 'Banco 1'), ('Banco 2', 'Banco 2'), ('Banco 3', 'Banco 3'), ('Banco 4', 'Banco 4')], max_length=30)),
                ('conta', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('operacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id_endereco', models.IntegerField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=8)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=80)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('observacoes', models.TextField()),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id_uf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_uf', models.CharField(max_length=30)),
                ('sigla_uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.IntegerField(primary_key=True, serialize=False)),
                ('vinculo', models.CharField(choices=[('Vinculo 1', 'Vinculo 1'), ('Vinculo 2', 'Vinculo 2')], max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('id_conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco.conta')),
                ('id_endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco.enderecos')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_ocorrencia', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('realizada', models.CharField(max_length=1)),
                ('ocorrencia', models.TextField()),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.uf'),
        ),
    ]
